game-info {
  filters {
    games_yy: Int
    games_dd: Int
    games_mm: Int
    games_stage: String
    games_ht: String
    games_at: String
    games_winner: String
    games_st: Long  #remove it


  }

  sorters {
    games_ts: Long
  }
}

game-stat {
  filters {
    teams_gameId: String

    teams_name: String

    teams_opponent: String
    teams_stage: String  #win|lose
    teams_st: Long
    outcome: String

    teams_pts: Int

    teams_ast: Int
    teams_blk: Int

    teams_mp: String
    teams_fg: Int
    teams_fga: Int
    teams_fgPct: Double
    teams_fg3: Int
    teams_fg3A: Int
    teams_fg3Pct: Double
    teams_ft: Int
    teams_fta: Int
    teams_ftPct: Double
  }

  sorters {
    teams_ts: Long
    teams_ast: Int
    teams_blk: Int

    teams_mp: String
    teams_fg: Int
    teams_fga: Int
    teams_fgPct: Double
    teams_fg3: Int
    teams_fg3A: Int
    teams_fg3Pct: Double
    teams_ft: Int
    teams_fta: Int
    teams_ftPct: Double
  }
}

player-stat {
  filters {
    players_gameId: String
    player_name: String
    players_stage: String
    players_fstage: String
    players_team: String
    players_loc: String
    players_opponent: String

    players_dd:Int,
    players_mm:Int,
    players_yy:Int,


    players_ast: Int    // assists
    players_blk: Int    // blocks
    players_stl: Int    // steals
    players_tov: Int    // turnovers
    players_trb: Int    // total rebounds
    players_pts: Int    // scored points
    players_fg: Int     // field goal
    players_fga: Int    // field goal attempts
    players_fgPct: Double  // field goal percentage
    players_fg3a: Int   // field goal 3 pointer attempts
    players_fg3Pct: Double // field goal 3 pointer percentage
  }

  sorters {
    players_ts: Long

    players_ast: Int    // assists
    players_blk: Int    // blocks
    players_stl: Int    // steals
    players_tov: Int    // turnovers
    players_trb: Int    // total rebounds
    players_pts: Int    // scored points
    players_fg: Int     // field goal
    players_fga: Int    // field goal attempts
    players_fgPct: Double  // field goal percentage
    players_fg3a: Int   // field goal 3 pointer attempts
    players_fg3Pct: Double // field goal 3 pointer percentage
  }
}