
filters: [

  { "games_ht"  : String }
  { "games_at" : String }
  { "games_stage" : String }
  { "games_winner" : String }
  { "games_yy" : Int }
  { "games_dd" : Int }
  { "games_mm" : Int }
]

sorters: [
  { "games_ts" : Long }
]

