filters {

  year {
    column_name: games_yy
    type: Int
  }

  day {
    column_name: games_dd
    type: Int
  }

  month {
    column_name: games_mm
    type: Int
  }

  stage {
    column_name: games_stage
    type: String
  }

  homeTeam {
    column_name: games_ht
    type: String
  }

  vistorTeam {
    column_name: games_at
    type: String
  }

  winner {
    column_name: games_winner
    type: String
  }
}

sorters {

  gameTime {
    column_name: games_ts
    type: Long
  }

}
