filters: [

  { "games_yy" : "Long" }
  { "games_dd" : "Long" }
  { "games_mm" : "Long" }
  { "games_stage" : "String" }
  { "games_ht"  : "String" }
  { "games_at" : "String" }
  { "games_winner" : "String" }
]

sorters: [
  { "games_ts" : "Long" }
]

